### ISSUE TITLE
Paredit-everywhere clobbering new search bindings

### ISSUE THREAD

**Issue by dakrone** [purcell/paredit-everywhere#5]
I'd like to use paredit-everywhere, but I'm a heavy user of the new search bindings in Emacs 25.1 that start with `M-s` (like `M-s .` for searching for the symbol at point).

I've tried to set the `M-s` binding in the `paredit-everywhere-mode-map` to nil to unbind it, but it's still bound for the map.

Is there a way to set this so it doesn't clobber the existing search bindings?

**Comment by purcell** [comment]
Hmm. You should be able to write:
```
(eval-after-load 'paredit-everywhere
  '(define-key paredit-everywhere-mode-map (kbd "M-s") nil))
```

I'd be surprised if that doesn't work.

The binding is also present in `paredit` itself, so this is a wider issue than `paredit-everywhere`. Both libraries should probably be fixed.

**Comment by dakrone** [comment]
That seems to do it!

I was originally trying to do it with `use-package` but couldn't get it to work.

Definitely agree on fixing paredit though, I'll try to track down and open a bug report for it. Thanks!

**Comment by purcell** [comment]
I've had a personal "TODO" for quite a while to start using the "standard" `M-s`, but the paredit version is actually trained into my fingers at this stage. If you get any traction with paredit, let me know, and I'll change paredit-everywhere to match.
